/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VkycAgent {
    }
    interface VkycApp {
    }
    /**
     * vkyc-applicant
     * Theme: #0d1b3e navy header · #f5f0eb warm beige bg · #ffffff cards · #00897b teal CTA
     * UX improvements over original:
     *  - Camera preview shows from step 1 (matches original)
     *  - Replaced captcha with clean step flow
     *  - 6 granular consents instead of 1 combined
     *  - Progress bar across top
     *  - Friendly copy, clear instructions
     *  - Countdown + liveness before agent connect
     *  - Warm completion screen with reference ID
     */
    interface VkycApplicant {
    }
    interface VkycAuditor {
    }
}
declare global {
    interface HTMLVkycAgentElement extends Components.VkycAgent, HTMLStencilElement {
    }
    var HTMLVkycAgentElement: {
        prototype: HTMLVkycAgentElement;
        new (): HTMLVkycAgentElement;
    };
    interface HTMLVkycAppElement extends Components.VkycApp, HTMLStencilElement {
    }
    var HTMLVkycAppElement: {
        prototype: HTMLVkycAppElement;
        new (): HTMLVkycAppElement;
    };
    /**
     * vkyc-applicant
     * Theme: #0d1b3e navy header · #f5f0eb warm beige bg · #ffffff cards · #00897b teal CTA
     * UX improvements over original:
     *  - Camera preview shows from step 1 (matches original)
     *  - Replaced captcha with clean step flow
     *  - 6 granular consents instead of 1 combined
     *  - Progress bar across top
     *  - Friendly copy, clear instructions
     *  - Countdown + liveness before agent connect
     *  - Warm completion screen with reference ID
     */
    interface HTMLVkycApplicantElement extends Components.VkycApplicant, HTMLStencilElement {
    }
    var HTMLVkycApplicantElement: {
        prototype: HTMLVkycApplicantElement;
        new (): HTMLVkycApplicantElement;
    };
    interface HTMLVkycAuditorElement extends Components.VkycAuditor, HTMLStencilElement {
    }
    var HTMLVkycAuditorElement: {
        prototype: HTMLVkycAuditorElement;
        new (): HTMLVkycAuditorElement;
    };
    interface HTMLElementTagNameMap {
        "vkyc-agent": HTMLVkycAgentElement;
        "vkyc-app": HTMLVkycAppElement;
        "vkyc-applicant": HTMLVkycApplicantElement;
        "vkyc-auditor": HTMLVkycAuditorElement;
    }
}
declare namespace LocalJSX {
    interface VkycAgent {
    }
    interface VkycApp {
    }
    /**
     * vkyc-applicant
     * Theme: #0d1b3e navy header · #f5f0eb warm beige bg · #ffffff cards · #00897b teal CTA
     * UX improvements over original:
     *  - Camera preview shows from step 1 (matches original)
     *  - Replaced captcha with clean step flow
     *  - 6 granular consents instead of 1 combined
     *  - Progress bar across top
     *  - Friendly copy, clear instructions
     *  - Countdown + liveness before agent connect
     *  - Warm completion screen with reference ID
     */
    interface VkycApplicant {
    }
    interface VkycAuditor {
    }
    interface IntrinsicElements {
        "vkyc-agent": VkycAgent;
        "vkyc-app": VkycApp;
        "vkyc-applicant": VkycApplicant;
        "vkyc-auditor": VkycAuditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vkyc-agent": LocalJSX.IntrinsicElements["vkyc-agent"] & JSXBase.HTMLAttributes<HTMLVkycAgentElement>;
            "vkyc-app": LocalJSX.IntrinsicElements["vkyc-app"] & JSXBase.HTMLAttributes<HTMLVkycAppElement>;
            /**
             * vkyc-applicant
             * Theme: #0d1b3e navy header · #f5f0eb warm beige bg · #ffffff cards · #00897b teal CTA
             * UX improvements over original:
             *  - Camera preview shows from step 1 (matches original)
             *  - Replaced captcha with clean step flow
             *  - 6 granular consents instead of 1 combined
             *  - Progress bar across top
             *  - Friendly copy, clear instructions
             *  - Countdown + liveness before agent connect
             *  - Warm completion screen with reference ID
             */
            "vkyc-applicant": LocalJSX.IntrinsicElements["vkyc-applicant"] & JSXBase.HTMLAttributes<HTMLVkycApplicantElement>;
            "vkyc-auditor": LocalJSX.IntrinsicElements["vkyc-auditor"] & JSXBase.HTMLAttributes<HTMLVkycAuditorElement>;
        }
    }
}
